services:
  vector:
    build: .
    volumes:
      - ./input.log:/etc/vector/input.log:ro
      - ./logs:/var/log:rw
    environment:
      - ELASTICSEARCH_IP=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - elastic_network

networks:
  elastic_network:
    driver: bridge